service:
  name: serverless-html-to-pdf
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1
  profile: serverless
  stackName: sls-html-to-pdf-stack
  apiGateway:
   binaryMediaTypes: # Optional binary media types the API might return
     - 'application/pdf'  

functions:
  generatePdf:
    handler: handler.generatePdf
    events:
      - http:
          method: get
          path: generatePdf
          parameters:
            headers:
              Accept: "application/pdf"